# Generated by Django 5.2.7 on 2026-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('name', models.CharField(max_length=200, verbose_name=' اسم مربی')),
                ('image', models.ImageField(upload_to='teacher/', verbose_name='تصویر')),
                ('courses_count', models.PositiveIntegerField(default=0, verbose_name='دوره مربوطه')),
                ('students_count', models.PositiveIntegerField(default=0, verbose_name='تعداد کارآموز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
