# Generated by Django 5.2.7 on 2026-06-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ins_modules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'مربی', 'verbose_name_plural': 'مربی ها'},
        ),
    ]
