# Generated by Django 5.2.7 on 2026-06-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_modules', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=300, null=True, verbose_name='عنوان در  url'),
        ),
    ]
