# Generated by Django 5.2.7 on 2026-06-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_modules', '0003_teacher_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='descreption',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
    ]
