# Generated by Django 5.2.7 on 2026-06-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_modules', '0004_teacher_descreption'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='لینک فیسبوک'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='لینک لینکدین'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.URLField(blank=True, null=True, verbose_name='لینک توییتر'),
        ),
    ]
