# Generated by Django 5.2.7 on 2026-06-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_modules', '0005_teacher_facebook_teacher_linkedin_teacher_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='twitter',
        ),
        migrations.AddField(
            model_name='teacher',
            name='gmail',
            field=models.URLField(blank=True, null=True, verbose_name='لینک جیمیل'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='phone_number',
            field=models.URLField(blank=True, null=True, verbose_name=' شماره تلفن'),
        ),
    ]
