# Generated by Django 5.2.7 on 2026-06-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ins_modules', '0006_remove_teacher_facebook_remove_teacher_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='instagram',
            field=models.CharField(blank=True, null=True, verbose_name='لینک اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone_number',
            field=models.CharField(blank=True, null=True, verbose_name=' شماره تلفن'),
        ),
    ]
