# Generated by Django 5.2.7 on 2026-06-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecomment',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات تکمیلی محصول'),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.CharField(default='نظر', verbose_name='موضوع نظر'),
        ),
    ]
