# Generated by Django 5.2.7 on 2026-06-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_modules', '0002_articlecomment_description_alter_articlecomment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecomment',
            name='description',
            field=models.TextField(null=True, verbose_name='توضیحات '),
        ),
        migrations.AlterField(
            model_name='articlecomment',
            name='text',
            field=models.CharField(max_length=200, verbose_name='موضوع نظر'),
        ),
    ]
