# Generated by Django 5.2.7 on 2026-06-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='برند')),
                ('is_Active', models.BooleanField(verbose_name='فعال/غیرفعال')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان')),
                ('url_title', models.CharField(db_index=True, max_length=300, verbose_name='عنوان در url')),
            ],
            options={
                'verbose_name': 'دسته بندی دوم',
                'verbose_name_plural': 'دستبندی ها',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200, verbose_name='عنوان تگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('short_description', models.CharField(db_index=True, max_length=400, null=True, verbose_name='توضیحات کوتاه')),
                ('description', models.TextField(null=True, verbose_name='توضیحات تکمیلی محصول')),
                ('image', models.ImageField(blank=True, db_index=True, default='', max_length=300, null=True, upload_to='product/', verbose_name=' تصویر ')),
                ('slug', models.CharField(blank=True, db_index=True, default='', max_length=300, null=True, verbose_name='عنوان در  url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف/نشده')),
                ('tool_dore', models.CharField(max_length=100, null=True, verbose_name='طول دوره')),
                ('talk', models.IntegerField(blank=True, null=True, verbose_name='کل سخرانی ها')),
                ('student', models.IntegerField(blank=True, null=True, verbose_name='کل دانش آموزان')),
                ('madrak', models.CharField(default=0, max_length=100, verbose_name='گواهینامه')),
                ('productBrand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_modules.productbrand', verbose_name='برند')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_model', to='product_modules.productmodel', verbose_name='دسته بندی دوره')),
                ('productTag', models.ManyToManyField(to='product_modules.producttag', verbose_name='تگ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصول ها',
            },
        ),
    ]
