# Generated by Django 5.2.7 on 2026-06-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_modules', '0002_remove_product_productbrand_productcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/'),
        ),
    ]
