# Generated by Django 5.2.7 on 2026-06-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_modules', '0004_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='twitter',
        ),
    ]
