# Generated by Django 5.2.7 on 2026-06-22 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_modules', '0005_remove_instructor_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_modules.instructor'),
        ),
    ]
