# Generated by Django 5.2.7 on 2026-06-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_modules', '0009_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='StudyPlan',
            field=models.TextField(null=True, verbose_name='برنامه تحصیلی'),
        ),
        migrations.AddField(
            model_name='product',
            name='overview',
            field=models.TextField(blank=True, max_length=200, verbose_name='بررسی اجمالی'),
        ),
    ]
