# Generated by Django 5.2.7 on 2026-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_modules', '0010_product_studyplan_product_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(db_index=True, default='temp-slug', max_length=300, verbose_name='عنوان در  url'),
            preserve_default=False,
        ),
    ]
