# Generated by Django 5.2.7 on 2026-06-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_modules', '0011_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(max_length=300, verbose_name='عنوان در  url'),
        ),
    ]
