# Generated by Django 5.2.7 on 2026-06-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footerlink',
            options={'verbose_name': 'لینک فوتر', 'verbose_name_plural': 'لینک های فوتر'},
        ),
    ]
