# Generated by Django 5.2.7 on 2026-06-20 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('title_url', models.CharField(max_length=200, verbose_name='عنوان در url')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال/ غیرفعال')),
                ('image', models.ImageField(blank=True, db_index=True, default='', max_length=300, null=True, upload_to='', verbose_name=' تصویر ')),
            ],
        ),
    ]
