# Generated by Django 5.2.7 on 2026-02-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='موضوع تو')),
                ('email', models.EmailField(max_length=200, verbose_name='ایمیل شما')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('message', models.TextField(max_length=500, verbose_name='پیغام تو')),
                ('admin_message', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('is_read_admin', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پیام')),
            ],
            options={
                'verbose_name': 'تماس با ما ',
                'verbose_name_plural': 'لیست تماس با ما',
            },
        ),
    ]
